-- FRESH SUPABASE PROJECT ONLY. Not safe for repeat application to an existing store.
-- Use Supabase SQL Editor; review and back up first.

-- ==================== 001_legacy_baseline.sql ====================
-- Additive baseline. Existing tables and identifiers are retained.
begin;
create extension if not exists pgcrypto;
create table if not exists users (id uuid primary key default gen_random_uuid(), email text unique not null, password_hash text, name text not null default '', phone text, address text, is_admin boolean not null default false, email_verified boolean default false, google_id text, created_at timestamptz default now());
create table if not exists categories (id bigint generated by default as identity primary key, name text not null, slug text unique, description text, image_url text, created_at timestamptz default now());
create table if not exists artisans (id bigint generated by default as identity primary key, name text not null, bio text, specialty text, location text, image_url text, active boolean default true, created_at timestamptz default now());
create table if not exists products (id uuid primary key default gen_random_uuid(), title text not null, description text, price numeric(12,2) not null check(price>=0), discount_percent integer default 0 check(discount_percent between 0 and 100), stock integer default 0 check(stock>=0), category_id bigint references categories(id), artisan_id bigint references artisans(id), featured boolean default false, is_flash_sale boolean default false, flash_sale_ends_at timestamptz, allow_preorder boolean default false, is_listed boolean default true, crafting_days integer default 7, images jsonb default '[]', created_at timestamptz default now());
create table if not exists variants (id bigint generated by default as identity primary key, product_id uuid references products(id), name text not null, value text not null, price_modifier numeric(12,2) default 0, stock integer default 0, sku text, created_at timestamptz default now());
create table if not exists coupons (id bigint generated by default as identity primary key, code text unique not null, discount_percent numeric default 0, active boolean default true, used_count integer default 0, max_uses integer, expires_at timestamptz, created_at timestamptz default now());
create table if not exists orders (id uuid primary key default gen_random_uuid(), user_id uuid references users(id), name text, phone text, address text, total numeric(12,2) not null default 0, status text default 'placed', coupon_code text, discount_amount numeric default 0, delivery_type text default 'delivery', shipping_charge numeric default 0, is_preorder boolean default false, preferred_delivery_date date, advance_amount numeric default 0, payment_screenshot_url text, is_custom_order boolean default false, custom_request_id uuid, custom_notes text, created_at timestamptz default now());
create table if not exists order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references orders(id), product_id uuid references products(id), title text not null, price numeric(12,2) not null, quantity integer not null check(quantity>0), image_url text, is_custom boolean default false);
create table if not exists tracking (id bigint generated by default as identity primary key, order_id uuid not null references orders(id), status text, note text, created_at timestamptz default now());
create table if not exists notifications (id bigint generated by default as identity primary key, user_id uuid references users(id), message text, link text, read boolean default false, created_at timestamptz default now());
create table if not exists reviews (id bigint generated by default as identity primary key, product_id uuid references products(id), user_id uuid references users(id), rating integer check(rating between 1 and 5), comment text, created_at timestamptz default now(), unique(product_id,user_id));
create table if not exists wishlists (id bigint generated by default as identity primary key, user_id uuid references users(id), product_id uuid references products(id), created_at timestamptz default now(), unique(user_id,product_id));
create table if not exists settings (key text primary key, value text);
create table if not exists custom_requests (id uuid primary key default gen_random_uuid(), user_id uuid references users(id), name text, email text, phone text, description text, budget text, craft_type text, occasion text, size_preference text, colour_preference text, reference_image_url text, tracking_token text unique, preferred_delivery_date date, status text default 'pending', quoted_price numeric, admin_note text, customer_response text, converted_order_id uuid references orders(id), linked_product_id uuid references products(id), created_at timestamptz default now());
create table if not exists raw_materials (id bigint generated by default as identity primary key, name text not null, category text, unit text default 'pcs', current_stock numeric not null default 0 check(current_stock>=0), reorder_level numeric default 0, cost_per_unit numeric default 0, supplier text, notes text, icon text, created_at timestamptz default now());
create table if not exists components (id bigint generated by default as identity primary key, name text not null, description text, unit text default 'pcs', current_stock numeric not null default 0 check(current_stock>=0), reorder_level numeric default 0, icon text, created_at timestamptz default now());
create table if not exists component_bom (id bigint generated by default as identity primary key, component_id bigint references components(id), material_id bigint references raw_materials(id), quantity_used numeric not null check(quantity_used>0));
create table if not exists product_bom (id bigint generated by default as identity primary key, product_id uuid references products(id), item_type text check(item_type in ('material','component')), material_id bigint references raw_materials(id), component_id bigint references components(id), quantity_used numeric not null check(quantity_used>0));
create table if not exists product_materials (id bigint generated by default as identity primary key, product_id uuid references products(id), material_id bigint references raw_materials(id), quantity_used numeric not null);
create table if not exists product_costs (id bigint generated by default as identity primary key, product_id uuid unique references products(id), labour_cost numeric default 0, overhead_cost numeric default 0, margin_percent numeric default 30, updated_at timestamptz default now());
create table if not exists expenditures (id bigint generated by default as identity primary key, material_id bigint references raw_materials(id), quantity numeric, cost_per_unit numeric, total_cost numeric, supplier text, notes text, purchased_at timestamptz default now());
create table if not exists manufacture_log (id bigint generated by default as identity primary key, component_id bigint references components(id), quantity_made numeric, wastage_percent numeric default 0, waste_cost numeric default 0, notes text, manufactured_at timestamptz default now());
create table if not exists order_requirements (id bigint generated by default as identity primary key, order_id uuid references orders(id), item_type text, material_id bigint references raw_materials(id), component_id bigint references components(id), quantity_needed numeric);
create table if not exists auth_tokens (id uuid primary key default gen_random_uuid(), user_id uuid references users(id), token text unique not null, type text not null, expires_at timestamptz not null, used boolean default false, created_at timestamptz default now());
create table if not exists gift_cards (id bigint generated by default as identity primary key, code text unique not null, amount numeric not null, balance numeric not null check(balance>=0), active boolean default true, recipient_email text, recipient_name text, message text, expires_at timestamptz, created_at timestamptz default now());
create table if not exists returns (id uuid primary key default gen_random_uuid(), order_id uuid references orders(id), user_id uuid references users(id), reason text, status text default 'pending', admin_note text, created_at timestamptz default now());
create table if not exists faqs (id bigint generated by default as identity primary key, question text, answer text, sort_order integer default 0, active boolean default true, created_at timestamptz default now());
create table if not exists broadcasts (id bigint generated by default as identity primary key, subject text, body text, sent_to integer, created_at timestamptz default now());
create table if not exists back_in_stock_alerts (id bigint generated by default as identity primary key, product_id uuid references products(id), user_id uuid references users(id), email text, notified boolean default false, created_at timestamptz default now());
create table if not exists email_templates (key text primary key, subject text, body_html text, updated_at timestamptz default now());
create table if not exists email_log (id bigint generated by default as identity primary key, to_email text, subject text, body text, sent_by uuid references users(id), related_type text, related_id text, sent_at timestamptz default now());
commit;


-- ==================== 002_commerce.sql ====================
begin;
alter table products add column if not exists availability_mode text;
alter table products add column if not exists accepting_orders boolean not null default true;
alter table products add column if not exists lead_time_max integer;
alter table products add column if not exists lead_time_min integer;
alter table products add column if not exists max_order_quantity integer default 99;
alter table products add column if not exists sale_price numeric(12,2);
alter table products add column if not exists slug text;
alter table products add column if not exists personalization_fields jsonb not null default '[]';
alter table products add column if not exists preorder_opens date;
alter table products add column if not exists preorder_closes date;
alter table products add column if not exists expected_dispatch_date date;
update products set availability_mode=case when not coalesce(is_listed,true) then 'DRAFT' when stock>0 then 'READY_TO_SHIP' when allow_preorder then 'MADE_TO_ORDER' else 'UNAVAILABLE' end where availability_mode is null;
alter table products alter column availability_mode set default 'READY_TO_SHIP';
alter table products add constraint products_availability_check check(availability_mode in ('READY_TO_SHIP','MADE_TO_ORDER','PREORDER','ONE_OF_ONE','CUSTOM_ONLY','UNAVAILABLE','DRAFT','ARCHIVED'));
alter table orders alter column user_id drop not null;
alter table orders add column if not exists email text;
alter table orders add column if not exists tracking_token text;
alter table orders add column if not exists idempotency_key text;
alter table orders add column if not exists payment_status text not null default 'unpaid';
alter table orders add column if not exists fulfilment_status text not null default 'order_received';
alter table orders add column if not exists gift_message text;
alter table orders add column if not exists order_notes text;
alter table orders add column if not exists inventory_consumed boolean not null default false;
alter table orders add column if not exists inventory_restored boolean not null default false;
alter table orders add column if not exists gift_card_code text;
alter table orders add column if not exists gift_card_discount numeric default 0;
create unique index if not exists orders_tracking_token_idx on orders(tracking_token);
create unique index if not exists orders_idempotency_idx on orders(idempotency_key);
alter table order_items add column if not exists variant_ids jsonb not null default '[]';
alter table order_items add column if not exists selected_options jsonb not null default '[]';
alter table order_items add column if not exists personalization jsonb not null default '{}';
alter table order_items add column if not exists availability_mode text;
alter table coupons add column if not exists discount_type text default 'percentage';
alter table coupons add column if not exists discount_value numeric default 0;
alter table coupons add column if not exists minimum_order_value numeric default 0;
alter table coupons add column if not exists maximum_discount numeric;
alter table coupons add column if not exists usage_limit integer;
alter table coupons add column if not exists max_uses integer;
update coupons set usage_limit=max_uses where usage_limit is null and max_uses is not null;
alter table coupons add column if not exists starts_at timestamptz;
create table if not exists newsletter_subscribers(email text primary key, active boolean not null default true, created_at timestamptz default now());
create table if not exists inventory_movements(id bigint generated always as identity primary key, item_type text not null, item_id text not null, quantity numeric not null, previous_quantity numeric, resulting_quantity numeric, movement_type text not null, order_id uuid references orders(id), actor_id uuid references users(id), note text, created_at timestamptz default now());
create table if not exists audit_log(id bigint generated always as identity primary key, actor_id uuid references users(id), action text not null, entity text not null, entity_id text, metadata jsonb default '{}', created_at timestamptz default now());
create index if not exists movements_order_idx on inventory_movements(order_id);
create index if not exists orders_user_created_idx on orders(user_id,created_at desc);
create index if not exists order_items_order_idx on order_items(order_id);
create index if not exists product_bom_product_idx on product_bom(product_id);
-- Server uses a service-role credential. No direct browser access to business tables.
do $$ declare t text; begin
 foreach t in array array['users','products','categories','coupons','variants','orders','order_items','tracking','notifications','reviews','wishlists','settings','custom_requests','raw_materials','components','component_bom','product_bom','product_materials','product_costs','expenditures','manufacture_log','order_requirements','auth_tokens','gift_cards','returns','faqs','broadcasts','back_in_stock_alerts','email_templates','email_log','artisans','newsletter_subscribers','inventory_movements','audit_log'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on public.%I from anon, authenticated',t);
 end loop;
end $$;
commit;


-- ==================== 003_transactions.sql ====================
begin;
create or replace function place_commerce_order(p_order jsonb,p_lines jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare o orders%rowtype; p products%rowtype; v variants%rowtype; c coupons%rowtype; g gift_cards%rowtype; gift_discount numeric=0; l jsonb; vid jsonb; opts jsonb; prepared jsonb='[]'; unit_price numeric; subtotal numeric=0; discount numeric=0; qty integer; entry jsonb; mode text; max_days integer=0;
begin
 if jsonb_array_length(p_lines)<1 or jsonb_array_length(p_lines)>100 then raise exception 'Invalid cart'; end if;
 perform pg_advisory_xact_lock(hashtextextended(p_order->>'idempotency_key',0));
 select * into o from orders where idempotency_key=p_order->>'idempotency_key';
 if found then return to_jsonb(o); end if;
 -- Stable lock order prevents two carts with reversed product order from deadlocking.
 perform 1 from products where id::text in (select value->>'product_id' from jsonb_array_elements(p_lines)) order by id for update;
 for l in select value from jsonb_array_elements(p_lines) loop
  select * into p from products where id::text=l->>'product_id';
  mode=p.availability_mode; qty=(l->>'quantity')::integer;
  if not found or not coalesce(p.is_listed,true) or not p.accepting_orders or mode not in ('READY_TO_SHIP','MADE_TO_ORDER','PREORDER','ONE_OF_ONE') then raise exception 'Product unavailable'; end if;
  if qty<1 or qty>least(coalesce(p.max_order_quantity,99),99) then raise exception 'Invalid quantity'; end if;
  if mode='PREORDER' and ((p.preorder_opens is not null and current_date<p.preorder_opens) or (p.preorder_closes is not null and current_date>p.preorder_closes)) then raise exception 'Preorder closed'; end if;
  if mode in ('READY_TO_SHIP','ONE_OF_ONE') then
   update products set stock=stock-qty where id=p.id and stock>=qty;
   if not found then raise exception 'Insufficient finished goods'; end if;
  end if;
  unit_price=coalesce(p.sale_price,round(p.price*(1-least(100,greatest(0,coalesce(p.discount_percent,0)))::numeric/100),2));
  opts='[]';
  for vid in select value from jsonb_array_elements(coalesce(l->'variant_ids','[]')) loop
   select * into v from variants where id::text=vid#>>'{}' and product_id=p.id;
   if not found then raise exception 'Invalid variant'; end if;
   if exists(select 1 from jsonb_array_elements(opts) x where x->>'name'=v.name) then raise exception 'Duplicate variant group'; end if;
   unit_price=unit_price+coalesce(v.price_modifier,0);
   opts=opts||jsonb_build_array(jsonb_build_object('id',v.id,'name',v.name,'value',v.value));
  end loop;
  if (select count(distinct name) from variants where product_id=p.id)<>jsonb_array_length(opts) then raise exception 'Missing variant'; end if;
  for entry in select value from jsonb_array_elements(p.personalization_fields) loop
   if coalesce((entry->>'required')::boolean,false) and coalesce(l->'personalization'->>(entry->>'name'),'')='' then raise exception 'Missing personalization'; end if;
  end loop;
  unit_price=greatest(0,round(unit_price,2)); subtotal=subtotal+unit_price*qty;
  max_days=greatest(max_days,coalesce(p.lead_time_max,p.crafting_days,0));
  prepared=prepared||jsonb_build_array(jsonb_build_object('product_id',p.id,'title',p.title,'price',unit_price,'quantity',qty,'image_url',coalesce(p.images->>0,''),'variant_ids',coalesce(l->'variant_ids','[]'),'selected_options',opts,'personalization',coalesce(l->'personalization','{}'),'availability_mode',mode));
 end loop;
 if nullif(p_order->>'preferred_delivery_date','') is not null and (p_order->>'preferred_delivery_date')::date<current_date+max_days+coalesce((select nullif(value,'')::integer from settings where key='processing_buffer'),0) then raise exception 'Delivery date too early'; end if;
 if nullif(p_order->>'coupon_code','') is not null then
  select * into c from coupons where code=upper(p_order->>'coupon_code') for update;
  if not found or not c.active or (c.expires_at is not null and c.expires_at<now()) or (c.starts_at is not null and c.starts_at>now()) or subtotal<coalesce(c.minimum_order_value,0) or (c.usage_limit is not null and coalesce(c.used_count,0)>=c.usage_limit) then raise exception 'Coupon invalid'; end if;
  discount=case when c.discount_type='fixed' then coalesce(c.discount_value,0) else round(subtotal*coalesce(c.discount_percent,0)/100,2) end;
  discount=greatest(0,least(subtotal,discount,coalesce(c.maximum_discount,subtotal)));
  update coupons set used_count=coalesce(used_count,0)+1 where id=c.id;
 end if;
 if nullif(p_order->>'gift_card_code','') is not null then
  select * into g from gift_cards where code=upper(p_order->>'gift_card_code') for update;
  if not found or not g.active or g.balance<=0 or (g.expires_at is not null and g.expires_at<now()) then raise exception 'Gift card invalid'; end if;
  gift_discount=least(g.balance,subtotal-discount);
  update gift_cards set balance=balance-gift_discount,active=(balance-gift_discount)>0 where id=g.id;
 end if;
 insert into orders(user_id,name,email,phone,address,total,status,coupon_code,discount_amount,delivery_type,preferred_delivery_date,tracking_token,idempotency_key,gift_message,order_notes,gift_card_code,gift_card_discount)
 values(nullif(p_order->>'user_id','')::uuid,p_order->>'name',p_order->>'email',p_order->>'phone',p_order->>'address',subtotal-discount-gift_discount,'placed',p_order->>'coupon_code',discount,p_order->>'delivery_type',nullif(p_order->>'preferred_delivery_date','')::date,p_order->>'tracking_token',p_order->>'idempotency_key',p_order->>'gift_message',p_order->>'order_notes',p_order->>'gift_card_code',gift_discount) returning * into o;
 for l in select value from jsonb_array_elements(prepared) loop
  insert into order_items(order_id,product_id,title,price,quantity,image_url,variant_ids,selected_options,personalization,availability_mode) values(o.id,(l->>'product_id')::uuid,l->>'title',(l->>'price')::numeric,(l->>'quantity')::integer,l->>'image_url',l->'variant_ids',l->'selected_options',l->'personalization',l->>'availability_mode');
  if l->>'availability_mode' in ('READY_TO_SHIP','ONE_OF_ONE') then
   insert into inventory_movements(item_type,item_id,quantity,movement_type,order_id,note) values('finished',l->>'product_id',-(l->>'quantity')::numeric,'order_reservation',o.id,'Finished piece allocated to order');
  end if;
 end loop;
 insert into tracking(order_id,status,note) values(o.id,'placed','Your order has been received. We will confirm preparation and payment details.');
 return to_jsonb(o);
end $$;

create or replace function consume_order_inventory(p_order_id uuid) returns boolean language plpgsql security definer set search_path=public as $$
declare o orders%rowtype; r record; before_qty numeric; after_qty numeric;
begin
 select * into o from orders where id=p_order_id for update;
 if not found or o.status='cancelled' then raise exception 'Order unavailable'; end if;
 if o.inventory_consumed then return true; end if;
 for r in select b.item_type,b.material_id,b.component_id,sum(b.quantity_used*i.quantity) needed from order_items i join product_bom b on b.product_id=i.product_id where i.order_id=p_order_id and coalesce(i.availability_mode,'MADE_TO_ORDER') in ('MADE_TO_ORDER','PREORDER','CUSTOM_ONLY') group by b.item_type,b.material_id,b.component_id order by b.item_type,b.material_id,b.component_id loop
  if r.item_type='material' then
   select current_stock into before_qty from raw_materials where id=r.material_id for update;
   if before_qty is null or before_qty<r.needed then raise exception 'Insufficient material'; end if;
   after_qty=before_qty-r.needed; update raw_materials set current_stock=after_qty where id=r.material_id;
  else
   select current_stock into before_qty from components where id=r.component_id for update;
   if before_qty is null or before_qty<r.needed then raise exception 'Insufficient component'; end if;
   after_qty=before_qty-r.needed; update components set current_stock=after_qty where id=r.component_id;
  end if;
  insert into inventory_movements(item_type,item_id,quantity,previous_quantity,resulting_quantity,movement_type,order_id) values(r.item_type,coalesce(r.material_id,r.component_id)::text,-r.needed,before_qty,after_qty,'order_consumption',p_order_id);
 end loop;
 update orders set inventory_consumed=true where id=p_order_id;
 return true;
end $$;

create or replace function cancel_commerce_order(p_order_id uuid) returns boolean language plpgsql security definer set search_path=public as $$
declare o orders%rowtype; r record;
begin
 select * into o from orders where id=p_order_id for update;
 if not found then raise exception 'Unknown order'; end if;
 if o.inventory_restored then return true; end if;
 if o.status in ('shipped','delivered') then raise exception 'Use return workflow for dispatched orders'; end if;
 -- Finished pieces can be returned to availability. Consumed craft materials cannot
 -- be assumed reusable; their disposition requires an explicit audited adjustment.
 for r in select * from inventory_movements where order_id=p_order_id and movement_type='order_reservation' order by item_id loop
  update products set stock=stock-r.quantity where id::text=r.item_id;
  insert into inventory_movements(item_type,item_id,quantity,movement_type,order_id) values('finished',r.item_id,-r.quantity,'cancellation_restock',p_order_id);
 end loop;
 update orders set status='cancelled',fulfilment_status='cancelled',inventory_restored=true where id=p_order_id;
 insert into tracking(order_id,status,note) values(p_order_id,'cancelled','Order cancelled. Any payment refund will be confirmed separately.');
 return true;
end $$;
create or replace function subscribe_newsletter(p_email text) returns boolean language plpgsql security definer set search_path=public as $$ begin insert into newsletter_subscribers(email) values(lower(p_email)) on conflict(email) do update set active=true; return true; end $$;
revoke all on function place_commerce_order(jsonb,jsonb),consume_order_inventory(uuid),cancel_commerce_order(uuid),subscribe_newsletter(text) from public,anon,authenticated;
grant execute on function place_commerce_order(jsonb,jsonb),consume_order_inventory(uuid),cancel_commerce_order(uuid),subscribe_newsletter(text) to service_role;
commit;


-- ==================== 004_inventory_operations.sql ====================
begin;
alter table raw_materials add column if not exists sku text;
alter table raw_materials add column if not exists supplier_sku text;
alter table raw_materials add column if not exists storage_location text;
alter table raw_materials add column if not exists active boolean not null default true;
alter table components add column if not exists active boolean not null default true;
alter table components add column if not exists notes text;
alter table expenditures add column if not exists note text;
alter table expenditures add column if not exists reference text;
alter table product_costs add column if not exists notes text;
alter table custom_requests add column if not exists quoted_days integer;
alter table custom_requests add column if not exists quote_message text;
alter table custom_requests add column if not exists quote_sent_at timestamptz;
create or replace function receive_material(p_data jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare result expenditures%rowtype; qty numeric; cpu numeric;
begin
 qty=(p_data->>'quantity')::numeric; cpu=(p_data->>'cost_per_unit')::numeric;
 if qty<=0 or cpu<0 then raise exception 'Invalid purchase'; end if;
 update raw_materials set current_stock=current_stock+qty,cost_per_unit=cpu where id=(p_data->>'material_id')::bigint;
 if not found then raise exception 'Material not found'; end if;
 insert into expenditures(material_id,quantity,cost_per_unit,total_cost,supplier,note,reference) values((p_data->>'material_id')::bigint,qty,cpu,qty*cpu,p_data->>'supplier',p_data->>'note',p_data->>'reference') returning * into result;
 return to_jsonb(result);
end $$;
create or replace function produce_component(p_component_id bigint,p_quantity numeric,p_wastage numeric,p_notes text) returns boolean language plpgsql security definer set search_path=public as $$
declare r record; need numeric; available numeric; waste_cost numeric=0;
begin
 if p_quantity<=0 or p_wastage<0 or p_wastage>100 then raise exception 'Invalid production quantity'; end if;
 perform 1 from components where id=p_component_id for update;
 if not found then raise exception 'Unknown component'; end if;
 if not exists(select 1 from component_bom where component_id=p_component_id) then raise exception 'Define a component recipe first'; end if;
 for r in select b.material_id,sum(b.quantity_used) qty from component_bom b where component_id=p_component_id group by b.material_id order by b.material_id loop
  need=r.qty*p_quantity*(1+p_wastage/100);
  select current_stock into available from raw_materials where id=r.material_id for update;
  if available is null or available<need then raise exception 'Insufficient material'; end if;
  update raw_materials set current_stock=current_stock-need where id=r.material_id;
  waste_cost=waste_cost+coalesce((select cost_per_unit from raw_materials where id=r.material_id),0)*r.qty*p_quantity*p_wastage/100;
 end loop;
 update components set current_stock=current_stock+p_quantity where id=p_component_id;
 insert into manufacture_log(component_id,quantity_made,wastage_percent,waste_cost,notes) values(p_component_id,p_quantity,p_wastage,waste_cost,p_notes);
 return true;
end $$;
-- Capture all stock edits, including legacy adjustment screens. Explicit order
-- movements retain order context; this trigger is a complete quantity audit.
create or replace function record_stock_change() returns trigger language plpgsql set search_path=public as $$
begin
 if new.current_stock is distinct from old.current_stock then
  if new.current_stock<0 then raise exception 'Inventory cannot be negative'; end if;
  insert into inventory_movements(item_type,item_id,quantity,previous_quantity,resulting_quantity,movement_type) values(case when tg_table_name='components' then 'component' else 'material' end,new.id::text,new.current_stock-old.current_stock,old.current_stock,new.current_stock,'balance_change');
 end if;
 return new;
end $$;
create trigger raw_material_balance_audit after update of current_stock on raw_materials for each row execute function record_stock_change();
create trigger component_balance_audit after update of current_stock on components for each row execute function record_stock_change();
revoke all on function receive_material(jsonb),produce_component(bigint,numeric,numeric,text) from public,anon,authenticated;
grant execute on function receive_material(jsonb),produce_component(bigint,numeric,numeric,text) to service_role;
commit;


-- ==================== 005_merchandising.sql ====================
begin;
create table if not exists collections(id bigint generated by default as identity primary key,name text not null,slug text unique not null,description text,image_url text,featured boolean default false,active boolean default true,created_at timestamptz default now());
create table if not exists occasions(id bigint generated by default as identity primary key,name text not null,slug text unique not null,image_url text,active boolean default true,created_at timestamptz default now());
create table if not exists collection_products(collection_id bigint references collections(id),product_id uuid references products(id),primary key(collection_id,product_id));
create table if not exists product_occasions(occasion_id bigint references occasions(id),product_id uuid references products(id),primary key(occasion_id,product_id));
alter table reviews add column if not exists visible boolean default true;
alter table reviews add column if not exists verified_purchase boolean default false;
alter table gift_cards add column if not exists issued_to text;
alter table artisans add column if not exists speciality text;
alter table artisans add column if not exists instagram text;
alter table faqs add column if not exists category text;
alter table orders add column if not exists internal_notes text;
alter table custom_requests add column if not exists listed_in_shop boolean default false;
create table if not exists testimonials(id bigint generated by default as identity primary key,name text not null,quote text not null,active boolean default true,created_at timestamptz default now());
do $$ declare t text; begin foreach t in array array['collections','occasions','collection_products','product_occasions','testimonials'] loop execute format('alter table %I enable row level security',t);execute format('revoke all on %I from anon,authenticated',t);end loop;end $$;
commit;


-- ==================== 006_custom_conversion.sql ====================
begin;
create or replace function convert_custom_request(p_request_id uuid,p_price numeric,p_note text default '') returns jsonb language plpgsql security definer set search_path=public as $$
declare r custom_requests%rowtype; o orders%rowtype; p products%rowtype;
begin
 if p_price<=0 then raise exception 'Quote must be positive'; end if;
 select * into r from custom_requests where id=p_request_id for update;
 if not found then raise exception 'Unknown request'; end if;
 if r.converted_order_id is not null then select * into o from orders where id=r.converted_order_id;return to_jsonb(o);end if;
 if r.status in ('closed','rejected') then raise exception 'Request is closed';end if;
 if r.linked_product_id is not null then select * into p from products where id=r.linked_product_id;end if;
 insert into orders(user_id,name,email,phone,address,total,status,is_custom_order,custom_request_id,custom_notes,tracking_token,preferred_delivery_date,internal_notes)
 values(r.user_id,r.name,r.email,r.phone,'To be confirmed',p_price,'placed',true,r.id,r.description,encode(gen_random_bytes(32),'hex'),r.preferred_delivery_date,p_note) returning * into o;
 insert into order_items(order_id,product_id,title,price,quantity,image_url,is_custom,availability_mode,personalization)
 values(o.id,r.linked_product_id,coalesce(p.title,r.craft_type,'Custom creation'),p_price,1,coalesce(p.images->>0,r.reference_image_url,''),true,'MADE_TO_ORDER',jsonb_build_object('request',r.description,'colours',r.colour_preference,'occasion',r.occasion));
 update custom_requests set status='converted',converted_order_id=o.id,quoted_price=p_price where id=r.id;
 insert into tracking(order_id,status,note) values(o.id,'placed','Your custom creation has been confirmed. We will share the next steps.');
 return to_jsonb(o);
end $$;
revoke all on function convert_custom_request(uuid,numeric,text) from public,anon,authenticated;
grant execute on function convert_custom_request(uuid,numeric,text) to service_role;
commit;


-- ==================== 007_order_states.sql ====================
begin;
-- Legacy status remains a compatibility field for existing screens/emails.
create or replace function sync_order_states() returns trigger language plpgsql as $$
begin
 if tg_op='INSERT' or new.status is distinct from old.status then
  if new.status in ('advance_requested','advance_paid','advance_confirmed') then
   new.payment_status=case new.status when 'advance_requested' then 'advance_requested' when 'advance_paid' then 'advance_submitted' else 'advance_verified' end;
  end if;
  if new.status in ('crafting','quality_check','shipped','delivered','cancelled') then new.fulfilment_status=new.status;
  elsif new.status='advance_confirmed' then new.fulfilment_status='confirmed';end if;
 elsif new.fulfilment_status is distinct from old.fulfilment_status then
  if new.fulfilment_status in ('crafting','quality_check','shipped','delivered','cancelled') then new.status=new.fulfilment_status;end if;
 end if;
 return new;
end $$;
create trigger orders_state_compatibility before insert or update on orders for each row execute function sync_order_states();
update orders set payment_status=case status when 'advance_requested' then 'advance_requested' when 'advance_paid' then 'advance_submitted' when 'advance_confirmed' then 'advance_verified' else payment_status end,
fulfilment_status=case when status in ('crafting','quality_check','shipped','delivered','cancelled') then status when status='advance_confirmed' then 'confirmed' else fulfilment_status end;
commit;


-- ==================== 008_order_validation.sql ====================
begin;
alter table orders add constraint orders_payment_status_check check(payment_status in ('unpaid','advance_requested','advance_submitted','advance_verified','partially_paid','paid','COD_due','refunded','partially_refunded','failed','cancelled'));
alter table orders add constraint orders_fulfilment_status_check check(fulfilment_status in ('order_received','awaiting_confirmation','confirmed','crafting','quality_check','ready_to_dispatch','shipped','out_for_delivery','ready_for_pickup','delivered','cancelled'));
create or replace function validate_fulfilment_transition() returns trigger language plpgsql as $$
declare allowed text[];
begin
 if new.fulfilment_status=old.fulfilment_status then return new;end if;
 allowed=case old.fulfilment_status
  when 'order_received' then array['awaiting_confirmation','confirmed','cancelled']
  when 'awaiting_confirmation' then array['confirmed','cancelled']
  when 'confirmed' then array['crafting','cancelled']
  when 'crafting' then array['quality_check','cancelled']
  when 'quality_check' then array['ready_to_dispatch','ready_for_pickup','shipped','cancelled']
  when 'ready_to_dispatch' then array['shipped','cancelled']
  when 'shipped' then array['out_for_delivery','delivered']
  when 'out_for_delivery' then array['delivered']
  when 'ready_for_pickup' then array['delivered','cancelled']
  else array[]::text[] end;
 if not new.fulfilment_status=any(allowed) then raise exception 'Invalid fulfilment transition';end if;
 return new;
end $$;
create trigger z_orders_validate_fulfilment before update on orders for each row execute function validate_fulfilment_transition();
commit;


-- ==================== 009_order_updates.sql ====================
begin;
create or replace function update_commerce_order(p_order_id uuid,p_data jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare current_order orders%rowtype; desired orders%rowtype;
begin
 select * into current_order from orders where id=p_order_id for update;
 if not found then raise exception 'Unknown order';end if;
 select * into desired from jsonb_populate_record(current_order,p_data);
 if desired.fulfilment_status='cancelled' or desired.status='cancelled' then
  perform cancel_commerce_order(p_order_id);
  select * into current_order from orders where id=p_order_id;
  return to_jsonb(current_order);
 end if;
 if desired.fulfilment_status='crafting' or desired.status='crafting' then perform consume_order_inventory(p_order_id);end if;
 if desired.total<0 or desired.shipping_charge<0 or desired.advance_amount<0 or desired.advance_amount>desired.total then raise exception 'Invalid order amount';end if;
 update orders set status=desired.status,payment_status=desired.payment_status,fulfilment_status=desired.fulfilment_status,total=desired.total,shipping_charge=desired.shipping_charge,advance_amount=desired.advance_amount,payment_screenshot_url=desired.payment_screenshot_url,internal_notes=desired.internal_notes where id=p_order_id returning * into current_order;
 return to_jsonb(current_order);
end $$;
revoke all on function update_commerce_order(uuid,jsonb) from public,anon,authenticated;
grant execute on function update_commerce_order(uuid,jsonb) to service_role;
commit;


-- ==================== 010_backend_permissions.sql ====================
begin;
-- BYPASSRLS does not imply table privileges. Grant only application tables.
do $$ declare t text; begin
 foreach t in array array['users','products','categories','coupons','variants','orders','order_items','tracking','notifications','reviews','wishlists','settings','custom_requests','raw_materials','components','component_bom','product_bom','product_materials','product_costs','expenditures','manufacture_log','order_requirements','auth_tokens','gift_cards','returns','faqs','broadcasts','back_in_stock_alerts','email_templates','email_log','artisans','newsletter_subscribers','inventory_movements','audit_log','collections','occasions','collection_products','product_occasions','testimonials'] loop
 execute format('grant select,insert,update,delete on public.%I to service_role',t);
 end loop;
end $$;
grant usage,select on all sequences in schema public to service_role;
commit;


-- ==================== 011_ui_metadata.sql ====================
-- Category archive/restore support. Existing categories remain active.
-- Public visibility additionally requires at least one published product.
begin;
alter table categories add column if not exists active boolean not null default true;
-- Optional per-image alternative text, aligned with the existing images array.
alter table products add column if not exists image_alt_texts jsonb not null default '[]';
commit;


-- ==================== 012_product_insert_repair.sql ====================
-- Everbloom: non-destructive product editor schema repair.
-- Apply ONCE in Supabase SQL Editor after a backup/staging verification.
-- Re-runnable: ADD COLUMN IF NOT EXISTS / GRANT are idempotent.
-- Does not modify existing product values, delete records or disable RLS.
-- This migration is useful if schema.sql previously stopped at migration 010.
begin;

-- These columns are sent by routes/admin.py::_parse_product_form on EVERY save.
-- The first columns originate in 002_commerce.sql; image_alt_texts is from 011.
alter table public.products
    add column if not exists availability_mode text default 'READY_TO_SHIP',
    add column if not exists accepting_orders boolean not null default true,
    add column if not exists lead_time_min integer,
    add column if not exists lead_time_max integer,
    add column if not exists max_order_quantity integer default 99,
    add column if not exists sale_price numeric(12,2),
    add column if not exists slug text,
    add column if not exists personalization_fields jsonb not null default '[]'::jsonb,
    add column if not exists image_alt_texts jsonb not null default '[]'::jsonb;

-- The backend key must be a service-role key; RLS remains enabled.
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.products to service_role;
commit;

-- PostgREST may otherwise keep an old cached schema for a short period.
notify pgrst, 'reload schema';

-- Verification (read-only):
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_schema='public' AND table_name='products'
-- AND column_name IN ('image_alt_texts','availability_mode','personalization_fields');


-- ==================== 013_custom_conversion_repair.sql ====================
-- Everbloom: idempotent custom-order conversion RPC repair (migration 013).
-- Back up first. Run in Supabase SQL Editor as project owner/postgres.
-- Does not touch existing orders, change RLS, or create customer orders.
-- Requires migrations 001 (tables) and, for full commerce features, 002–012.
BEGIN;

-- Only the columns the conversion RPC actually needs. On partially migrated
-- projects, these may be absent even though the base tables exist.
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS tracking_token text,
  ADD COLUMN IF NOT EXISTS internal_notes text;
ALTER TABLE public.order_items
  ADD COLUMN IF NOT EXISTS personalization jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS availability_mode text;

-- Preserve the API signature expected by models.convert_custom_to_order.
-- Fully qualified tables and pg_catalog first prevent SECURITY DEFINER
-- name resolution surprises. Use core gen_random_uuid() rather than
-- pgcrypto gen_random_bytes(), which may live in Supabase's extensions schema.
CREATE OR REPLACE FUNCTION public.convert_custom_request(
  p_request_id uuid,
  p_price numeric,
  p_note text DEFAULT ''
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  r public.custom_requests%ROWTYPE;
  o public.orders%ROWTYPE;
  p public.products%ROWTYPE;
  new_tracking_token text;
BEGIN
  IF p_request_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Request ID is required';
  END IF;
  IF p_price IS NULL OR p_price <= 0 OR p_price > 9999999999.99
     OR p_price <> round(p_price, 2) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Enter a positive agreed price with at most two decimal places';
  END IF;

  -- Lock request row, making repeated clicks and concurrent retries idempotent.
  SELECT * INTO r FROM public.custom_requests WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Custom request does not exist';
  END IF;

  IF r.converted_order_id IS NOT NULL THEN
    SELECT * INTO o FROM public.orders WHERE id = r.converted_order_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'Request points to a missing converted order; contact an administrator';
    END IF;
    RETURN to_jsonb(o);
  END IF;

  IF r.status IN ('closed', 'rejected') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Closed or rejected requests cannot be converted';
  END IF;

  IF r.linked_product_id IS NOT NULL THEN
    SELECT * INTO p FROM public.products WHERE id = r.linked_product_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'Linked product no longer exists';
    END IF;
  END IF;

  -- gen_random_uuid is built into supported PostgreSQL versions, so no
  -- dependency on pgcrypto extension location. Two UUIDv4s yield a 64-char token.
  new_tracking_token := replace(gen_random_uuid()::text, '-', '') ||
                        replace(gen_random_uuid()::text, '-', '');

  INSERT INTO public.orders (
    user_id, name, email, phone, address, total, status,
    is_custom_order, custom_request_id, custom_notes, tracking_token,
    preferred_delivery_date, internal_notes
  ) VALUES (
    r.user_id, r.name, r.email, r.phone, 'To be confirmed', p_price,
    'placed', true, r.id, r.description, new_tracking_token,
    r.preferred_delivery_date, left(coalesce(p_note, ''), 20000)
  ) RETURNING * INTO o;

  INSERT INTO public.order_items (
    order_id, product_id, title, price, quantity, image_url,
    is_custom, availability_mode, personalization
  ) VALUES (
    o.id, r.linked_product_id,
    coalesce(p.title, r.craft_type, 'Custom creation'),
    p_price, 1, coalesce(p.images->>0, r.reference_image_url, ''),
    true, 'MADE_TO_ORDER',
    jsonb_build_object('request', r.description, 'colours', r.colour_preference, 'occasion', r.occasion)
  );

  UPDATE public.custom_requests
  SET status = 'converted', converted_order_id = o.id, quoted_price = p_price
  WHERE id = r.id;

  INSERT INTO public.tracking (order_id, status, note)
  VALUES (o.id, 'placed', 'Your custom creation has been confirmed. We will share the next steps.');

  RETURN to_jsonb(o);
END;
$$;

-- Keep execution restricted to the backend role; no public or browser RPC use.
REVOKE ALL ON FUNCTION public.convert_custom_request(uuid, numeric, text)
FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA public TO service_role;
GRANT EXECUTE ON FUNCTION public.convert_custom_request(uuid, numeric, text) TO service_role;
-- These grants also cover direct backend reads/edits. RLS is unchanged.
GRANT SELECT, UPDATE ON public.custom_requests TO service_role;
GRANT SELECT, INSERT ON public.orders, public.order_items, public.tracking TO service_role;
GRANT SELECT ON public.products TO service_role;
COMMIT;

-- Refresh the PostgREST function-signature/schema cache.
NOTIFY pgrst, 'reload schema';

-- Safe, read-only verification:
-- SELECT to_regprocedure('public.convert_custom_request(uuid,numeric,text)') AS rpc_signature;
-- SELECT column_name FROM information_schema.columns WHERE table_schema='public'
--   AND table_name='orders' AND column_name IN ('email','tracking_token','internal_notes');
-- SELECT has_function_privilege('service_role',
--   'public.convert_custom_request(uuid,numeric,text)', 'EXECUTE') AS service_role_can_execute;


-- ==================== 014_storage_setup.sql ====================
-- Everbloom: Supabase Storage prerequisites. Safe for existing data.
-- Run as the Supabase project owner in SQL Editor, after a backup.
-- Supabase's managed `storage` schema must already exist.
BEGIN;
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('everbloom', 'everbloom', true, 8388608, ARRAY['image/webp'])
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('payment-receipts', 'payment-receipts', false, 8388608, ARRAY['image/webp'])
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;
COMMIT;
-- All uploads/signing are made from the Flask backend with service_role.
-- Do not add public INSERT/UPDATE policies to payment-receipts.
-- Existing payment proof URLs require separate migration; this does not make old public objects private.


-- ==================== 015_coupon_rls_permissions.sql ====================
-- Critical security hardening: baseline coupons was omitted from grants/RLS lists.
-- Safe on existing Supabase projects. No coupon rows are deleted or rewritten.
BEGIN;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.coupons FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.coupons TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
COMMIT;
-- Browser clients must never access coupon inventory directly. The Flask
-- backend validates and consumes coupons within place_commerce_order RPC.

