begin;
alter table products add column if not exists availability_mode text;
alter table products add column if not exists accepting_orders boolean not null default true;
alter table products add column if not exists lead_time_max integer;
alter table products add column if not exists lead_time_min integer;
alter table products add column if not exists max_order_quantity integer default 99;
alter table products add column if not exists sale_price numeric(12,2);
alter table products add column if not exists slug text;
alter table products add column if not exists personalization_fields jsonb not null default '[]';
alter table products add column if not exists preorder_opens date;
alter table products add column if not exists preorder_closes date;
alter table products add column if not exists expected_dispatch_date date;
update products set availability_mode=case when not coalesce(is_listed,true) then 'DRAFT' when stock>0 then 'READY_TO_SHIP' when allow_preorder then 'MADE_TO_ORDER' else 'UNAVAILABLE' end where availability_mode is null;
alter table products alter column availability_mode set default 'READY_TO_SHIP';
alter table products add constraint products_availability_check check(availability_mode in ('READY_TO_SHIP','MADE_TO_ORDER','PREORDER','ONE_OF_ONE','CUSTOM_ONLY','UNAVAILABLE','DRAFT','ARCHIVED'));
alter table orders alter column user_id drop not null;
alter table orders add column if not exists email text;
alter table orders add column if not exists tracking_token text;
alter table orders add column if not exists idempotency_key text;
alter table orders add column if not exists payment_status text not null default 'unpaid';
alter table orders add column if not exists fulfilment_status text not null default 'order_received';
alter table orders add column if not exists gift_message text;
alter table orders add column if not exists order_notes text;
alter table orders add column if not exists inventory_consumed boolean not null default false;
alter table orders add column if not exists inventory_restored boolean not null default false;
alter table orders add column if not exists gift_card_code text;
alter table orders add column if not exists gift_card_discount numeric default 0;
create unique index if not exists orders_tracking_token_idx on orders(tracking_token);
create unique index if not exists orders_idempotency_idx on orders(idempotency_key);
alter table order_items add column if not exists variant_ids jsonb not null default '[]';
alter table order_items add column if not exists selected_options jsonb not null default '[]';
alter table order_items add column if not exists personalization jsonb not null default '{}';
alter table order_items add column if not exists availability_mode text;
alter table coupons add column if not exists discount_type text default 'percentage';
alter table coupons add column if not exists discount_value numeric default 0;
alter table coupons add column if not exists minimum_order_value numeric default 0;
alter table coupons add column if not exists maximum_discount numeric;
alter table coupons add column if not exists usage_limit integer;
alter table coupons add column if not exists max_uses integer;
update coupons set usage_limit=max_uses where usage_limit is null and max_uses is not null;
alter table coupons add column if not exists starts_at timestamptz;
create table if not exists newsletter_subscribers(email text primary key, active boolean not null default true, created_at timestamptz default now());
create table if not exists inventory_movements(id bigint generated always as identity primary key, item_type text not null, item_id text not null, quantity numeric not null, previous_quantity numeric, resulting_quantity numeric, movement_type text not null, order_id uuid references orders(id), actor_id uuid references users(id), note text, created_at timestamptz default now());
create table if not exists audit_log(id bigint generated always as identity primary key, actor_id uuid references users(id), action text not null, entity text not null, entity_id text, metadata jsonb default '{}', created_at timestamptz default now());
create index if not exists movements_order_idx on inventory_movements(order_id);
create index if not exists orders_user_created_idx on orders(user_id,created_at desc);
create index if not exists order_items_order_idx on order_items(order_id);
create index if not exists product_bom_product_idx on product_bom(product_id);
-- Server uses a service-role credential. No direct browser access to business tables.
do $$ declare t text; begin
 foreach t in array array['users','products','categories','coupons','variants','orders','order_items','tracking','notifications','reviews','wishlists','settings','custom_requests','raw_materials','components','component_bom','product_bom','product_materials','product_costs','expenditures','manufacture_log','order_requirements','auth_tokens','gift_cards','returns','faqs','broadcasts','back_in_stock_alerts','email_templates','email_log','artisans','newsletter_subscribers','inventory_movements','audit_log'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on public.%I from anon, authenticated',t);
 end loop;
end $$;
commit;
